name: workflow release
on: [workflow_dispatch]
jobs:

  build_computegen:
    name: build computegen
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: update submodules
        run: ls && git submodule update --init
      - name: restore, build, and run
        run: dotnet run --project src/computegen.csproj